### ISSUE TITLE
Proposal: next(null, null) -> next(null) to close a stream

### ISSUE THREAD

**Issue by yoshuawuyts** [hughsk/from2#10]
__summary__
I think we should loosen the close signature of `next(null, null)` to also accept `next(null, undefined)`.

__motivation__
Intuitively I assumed the closing signature would be `next(null)`, as is the case with [stream.Readable](https://nodejs.org/api/stream.html#stream_class_stream_readable_1) which requires `this.push(null)` to close a stream. I found it confusing that the signature was instead `next(null, null)`.

__detailed design__
Probably all that needs to happen is change a strict [index.js#L62](https://github.com/hughsk/from2/blob/master/index.js#L62) from `if (data === null)` to `if (!data)`.

__drawbacks__
The only caveat I can think of with a falsy check is that doing `cb(null, 0)` won't work, but that shouldn't be an issue with streams (e.g. it's generally only buffers / strings / objects). 
Maybe a slight impact on performance would happen (falsy check over strict equality OR an extra `if` statement), but I think the overhead would be negligable.

What do you think?

**Comment by mafintosh** [comment]
:+1:

**Comment by yoshuawuyts** [comment]
Hmm, I've had a little nap over this and I actually don't think we should do it. E.g.
```js
// stream.Writable close signature
this.push(data)
this.push(null)

// proposed from2 close signature
this.push(error, data)
this.push(null, undefined)
```
We'd be changing the requirement that `data === null` to close the stream, which I don't think is good. Gonna go ahead and close this one. Thanks for bearing with me! (':
