### ISSUE TITLE
may unexpectedly block event loop

### ISSUE THREAD

**Issue by davidmarkclements** [hughsk/from2#18]
```js
'use strict'

var from = require('from2')
var tick = 0
var stream = from.obj(function (size, cb) {
  cb(null, {tick: tick++})
})

stream.once('data', function (data)  {
  console.log(data)
})

setTimeout(function () {
  process.exit()
}, 1000)
```

Expected behavior to print out `{"tick": 0}` and  for the process to exit after 1000 milliseconds, instead the process never exits because the (infinite) from stream is blocking the event loop (even though we use `once`)

**Comment by mafintosh** [comment]
This is how readable streams work (unfortunately). Once you add a data listener it enters flowing mode. After that it is your own responsibility to .pause/.resume the stream. Streams run in the same tick for perf reasons.
